project_id = "gsvthjtputwjqqkgwmeo"
[functions.enviar-factura]
enabled = true
verify_jwt = true
import_map = "./functions/enviar-factura/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/enviar-factura/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/enviar-factura/*.html" ]

[functions.insert-egreso]
enabled = true
verify_jwt = true
entrypoint = "./functions/insert-egreso/index.ts"

[functions.admin-create-user]
enabled = true
# Permitir bootstrap sin autenticaci√≥n cuando no hay usuarios creados
verify_jwt = false
entrypoint = "./functions/admin-create-user/index.ts"